# Generated by Django 5.2.17 on 2026-08-12 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive records are hidden from normal operation.')),
                ('product_code', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Product Code')),
                ('description', models.TextField(blank=True)),
                ('department', models.ForeignKey(help_text='Department this product belongs to.', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='departments.department')),
            ],
            options={
                'ordering': ['product_code'],
                'indexes': [models.Index(fields=['department'], name='products_pr_departm_dc7941_idx')],
            },
        ),
    ]
