# Generated by Django 5.2.17 on 2026-08-15 00:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive records are hidden from normal operation.')),
                ('product_code', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Product Code')),
                ('description', models.CharField(blank=True, max_length=500)),
                ('department', models.CharField(blank=True, max_length=255)),
                ('admin', models.ForeignKey(help_text='User who administers this product.', on_delete=django.db.models.deletion.PROTECT, related_name='products_administered', to=settings.AUTH_USER_MODEL)),
                ('buyer', models.ForeignKey(help_text='User who buys/procures this product.', on_delete=django.db.models.deletion.PROTECT, related_name='products_bought', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['product_code'],
                'indexes': [models.Index(fields=['department'], name='products_pr_departm_ea8d15_idx')],
            },
        ),
    ]
