# Generated by Django 5.2.17 on 2026-08-07 02:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive records are hidden from normal operation.')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('sku', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='SKU / Product Code')),
                ('category', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Standard selling price per unit.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('department', models.ForeignKey(help_text='Department this product belongs to.', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='departments.department')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name', 'sku'], name='products_pr_name_0f3349_idx'), models.Index(fields=['department'], name='products_pr_departm_dc7941_idx')],
            },
        ),
    ]
