# Generated by Django 5.2.17 on 2026-08-15 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive records are hidden from normal operation.')),
                ('start_date', models.DateField(db_index=True, help_text='Start of the reporting period.')),
                ('end_date', models.DateField(db_index=True, help_text='End of the reporting period.')),
                ('total_sales_qty', models.IntegerField()),
                ('total_sales_amt', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total_stock', models.IntegerField(help_text='Total stock on hand for this product/branch during the reporting period.')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_records', to='branches.branch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_records', to='products.product')),
            ],
            options={
                'verbose_name': 'Sales Data',
                'verbose_name_plural': 'Sales Data',
                'ordering': ['-start_date', '-created_at'],
                'indexes': [models.Index(fields=['branch', 'product', 'start_date'], name='sales_data__branch__5d524a_idx'), models.Index(fields=['start_date', 'end_date'], name='sales_data__start_d_13ff18_idx')],
                'constraints': [models.UniqueConstraint(fields=('product', 'branch', 'start_date', 'end_date'), name='unique_sales_data_product_branch_period')],
            },
        ),
    ]
