# Generated by Django 5.2.17 on 2026-08-12 08:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('buyers', '0001_initial'),
        ('departments', '0001_initial'),
        ('products', '0001_initial'),
        ('store_admins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive records are hidden from normal operation.')),
                ('description', models.TextField(blank=True, help_text='Product description as of this sales record.')),
                ('start_date', models.DateField(db_index=True, help_text='Start of the reporting period.')),
                ('end_date', models.DateField(db_index=True, help_text='End of the reporting period.')),
                ('total_sales_qty', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('total_sales_amt', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_stock', models.PositiveIntegerField(help_text='Total stock on hand for this product/branch during the reporting period.')),
                ('admin', models.ForeignKey(help_text='Store admin who recorded/manages this sale.', on_delete=django.db.models.deletion.PROTECT, related_name='sales_records', to='store_admins.storeadmin')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_records', to='branches.branch')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_records', to='buyers.buyer')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_records', to='departments.department')),
                ('product_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_records', to='products.product', verbose_name='Product Code')),
            ],
            options={
                'verbose_name': 'Sales Data',
                'verbose_name_plural': 'Sales Data',
                'ordering': ['-start_date', '-created_at'],
                'indexes': [models.Index(fields=['branch', 'product_code', 'start_date'], name='salesdata_s_branch__328fdc_idx'), models.Index(fields=['start_date', 'end_date'], name='salesdata_s_start_d_238ddb_idx'), models.Index(fields=['department'], name='salesdata_s_departm_82ac91_idx')],
                'constraints': [models.UniqueConstraint(fields=('product_code', 'branch', 'start_date', 'end_date'), name='unique_salesdata_product_branch_period')],
            },
        ),
    ]
